// Code generated by hand to imitar saída do gomock; não editar manualmente.
package mocks

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"github.com/vertikon/mcp-ultra-templates/internal/models"
)

// MockRepository implementa Repository para testes.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder grava expectations.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository cria uma nova instância mock.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT retorna o recorder.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ListTemplates define o mock.
func (m *MockRepository) ListTemplates(ctx context.Context) ([]models.TemplateMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx)
	ret0, _ := ret[0].([]models.TemplateMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates expectation.
func (mr *MockRepositoryMockRecorder) ListTemplates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockRepository)(nil).ListTemplates), ctx)
}

// LoadTemplate define o mock.
func (m *MockRepository) LoadTemplate(ctx context.Context, name string) (*models.TemplateMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTemplate", ctx, name)
	ret0, _ := ret[0].(*models.TemplateMetadata)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadTemplate expectation.
func (mr *MockRepositoryMockRecorder) LoadTemplate(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTemplate", reflect.TypeOf((*MockRepository)(nil).LoadTemplate), ctx, name)
}

